version: "3.8"

services:
  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
    depends_on:
      - server
    networks:
      - minio-local

  minio:
    container_name: minio
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=chair-admin
      - MINIO_ROOT_PASSWORD=chair-password
    volumes:
      - minio-storage:/data
    networks:
      - minio-local

  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - sqlite3-db:./db/:./db/
    networks:
      - minio-local

  server:
    container_name: server
    build: .
    environment:
      - MINIO_HOST=127.0.0.1
      - MINIO_PORT=9000
      - MINIO_ROOT_USER=chair-admin
      - MINIO_ROOT_PASSWORD=chair-password
      - REMOTE_URL=127.0.0.1/minio-api
    depends_on:
      - minio
      - db
    networks:
      - minio-local


networks:
  minio-local:
    driver: bridge


volumes:
  minio-storage:
  sqlite3-db:
