version: "3.8"

services:
  minio:
    image: minio/minio:RELEASE.2023-11-01T18-37-25Z-cpuv1
    command: server --console-address ":9001" /data/
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=chair-admin
      - MINIO_ROOT_PASSWORD=chair-password
    networks:
      - minio-local
  server:
    container_name: server
    build: .
    ports:
      - 8080:8080
    environment:
      - MINIO_HOST=http://127.0.0.1:9000
      - MINIO_USER=chair-admin
      - MINIO_PASSWORD=chair-password
    networks:
      - minio-local


networks:
  minio-local:
    driver: bridge